### ISSUE TITLE
All Pages: Images don't fit in the blue bordered container in all pages. There is always a gap

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Blue-Print#30]
![product single - 02](https://cloud.githubusercontent.com/assets/11186359/9457446/0f0653e6-4b15-11e5-9904-cb58139cec65.jpg)

**Comment by maehtitan** [comment]
Not yet fixed
![image](https://cloud.githubusercontent.com/assets/13363508/9599737/ccba4862-50c8-11e5-9b27-74d0f12be85d.png)

**Comment by maehtitan** [comment]
Still not fixed

**Comment by nakul-titan** [comment]
Hi Maeh,

I have made sure it fixed everywhere. Could you please send me a screenshot at where you still see this bug.

Thanks

**Comment by maehtitan** [comment]
Hi @nakul-titan 

<b>Below is the sample image:</b>

![image](https://cloud.githubusercontent.com/assets/13363508/9707714/aad5eb88-5542-11e5-879f-c1b8686b1c86.png)

<b>The sample photo you used (http://blueprint.stage.titanweb.com.au/wp-content/uploads/2015/08/product-single-image-223x172.jpg) which doesn't have a white background from its bottom and top that's why you add padding which affected gallery page and the sample image we uploaded

![image](https://cloud.githubusercontent.com/assets/13363508/9707755/af28f9c2-5543-11e5-9ca0-c1ffa47073d9.png)

Removing the padding 10px will closely fit the image to its border.

That's what we mean that it's not yet fixed.

Upload an image with white background on its top, left, bottom and right and pls remove the padding.
